name: resistors

on:
  push:
    branches:
      - main
  workflow-dispatch:

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/setup-node@v3
  with:
    node-version: 14
    cache: 'npm'
    cache-dependency-path: '**/package-lock.json'
    - run: npm install -g @angular/cli@9
    - run: npm install
    - run: ng test
